---
title: "Homework5"
author: "Eurydice Aboagye"
date: "2023-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###Question 1  
Assign to the variable n_dims a single random integer between 3 and 10.

```{r} 
a<-c(seq(from=3, to=10))
print(a)

n_dims <-sample(x=a, size=1)

print(n_dims)

b<- c(seq(from=1, to=(n_dims)^2)) #Create a vector of consecutive integers from 1 to n_dims2

print(b)
#Use the sample function to randomly reshuffle these values.

x<-c(sample(x=b))

##create square matrix

m1<-(matrix(data=x,nrow=n_dims,ncol=n_dims))
m1
m2<-t(m1)## Transposed matrix
m2

#Calculate sum and mean of first and last row
sum(m2[1,])
mean(m2[1,])
sum(m2[n_dims,])
mean(m2[n_dims,])


#Eigen Function
m3<-eigen(m2, symmetric =TRUE, only.values=FALSE)
m3
typeof(m3)
typeof(m3$values)
typeof(m3$vectors)
```



###Question 2  
```{r} 
my_matrix<-(matrix(data=runif(16, min=1, max=20),nrow=4, ncol=4))
my_matrix #a 4x4 matrix filled with random uniform values

rand<-c(runif(n=100))
rand
my_logical <- rand<0.5
print(my_logical) # a 100 element vector of True or False values

alphabets<-c(letters[1:26])              
alphabets

my_letters<-c(sample(x=alphabets))
my_letters # a 26-element vector of all the lower-case letters in random order

my_list<-list(my_matrix, my_logical, my_letters)


#create a new list, which has the element[2,2] from the matrix, the second element of the logical vector, and the second element of the letters vector.

new_list<- list(my_matrix[2,2], my_logical[2], my_letters[2])

print(new_list)

typeof(new_list[[1]])
summary(new_list)


#new vector
new_vec<-c(new_list)
typeof(new_vec)
print(new_vec)
```



###Question 3  

```{r}

#Question 3
#Create a data frame with the two variables (= columns) and 26 cases (= rows) below

my_unis<-runif(26, min=0, max=10)
my_LETTERS<-LETTERS[1:26]
my_letters2<-sample(x=my_LETTERS)
My_frame<-data.frame(my_unis,my_letters2)

print(My_frame)

#for the first variable, use a single line of code in R to select 4 random rows and replace the numerical values in those rows with NA.

My_frame[sample(nrow(My_frame),4), 1]<-NA

My_frame[!complete.cases(My_frame[ ,c(1)]),] ## i used the complete.cases function to determine which rows in column 1 had missing values


My_frame2<-data.frame(my_unis, sort(my_letters2, decreasing = FALSE)) ##I used the sort function to reorder the second variable in alphabetical order
My_frame2


mean(My_frame2[ ,1]) #could not figure out how to use the colMean function so i used the normal mean function and specified column 1.

```







